name: Deploy Laravel App Preprod

on:
  push:
    branches:
      - 'release/*'  # ou la branche de ton choix pour le déploiement
  workflow_dispatch:

jobs:
  run-tests:
    uses: WillyJulien/laravel_api/.github/workflows/ci.yml@develop

  deploy:
    needs: run-tests
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_VPS }}

      - name: Deploy to VPS
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "Deploying branch: ${BRANCH_NAME}"
          ssh -o StrictHostKeyChecking=no ubuntu@91.134.90.115 << EOF
            cd /var/www/app/laravel_api_preprod || exit
            git pull origin ${BRANCH_NAME} || exit
            composer install --no-dev --optimize-autoloader || exit
            php artisan migrate --force || exit
            php artisan config:cache || exit
            php artisan route:cache || exit
            sudo systemctl restart nginx || exit
          EOF
