name: Deploy Laravel App

on:
  push:
    branches:
      - main  # ou la branche de ton choix pour le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_VPS }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@91.134.90.115 << 'EOF'
            cd /var/www/mon-app || exit
            git pull origin main || exit
            composer install --no-dev --optimize-autoloader || exit
            php artisan migrate --force || exit
            php artisan config:cache || exit
            php artisan route:cache || exit
            sudo systemctl restart nginx || exit
          EOF
